- id: HomeAssistant Update Available
  alias: "Home Asssistant Update Available"
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
    service: notify.slack_manorhaus
    data:
      message: "@here New version {{ states.updater.updater.state }} of Home Assistant is available. Now go do something about it."
##
##
- id: Upstairs Closet Light AutoOn
  alias: "Upstairs Closet Light AutoOn"
  trigger: 
  - platform: state
    entity_id: binary_sensor.upstairs_closet_sensor
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.upstairs_closet
  - service: notify.slack_manorhaus
    data:
      message: "I turned on the upstairs closet light because there was someone in there.  I thought it was the right thing to do."
###
- id: Pantry Light AutoOn
  alias: "Pantry Light AutoOn"
  trigger: 
  - platform: state
    entity_id: binary_sensor.pantry_door_sensor
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.pantry
  - service: notify.slack_manorhaus
    data:
      message: "Scatterbrain Jane is in the pantry so I turned the lights on.  I don't know why. I just do."
##
##
#- id: Pantry Light AutoOff
#  alias: "Pantry Light AutoOff"
#  trigger:
#  - platform: state
#    entity_id: light.pantry_1
#    to: 'on'
#    for:
#      minutes: 5
#  action:
#  - service: light.turn_off
#    entity_id: light.pantry
#  - service: notify.slack_manorhaus
#    data:
#      message: "Pantry light turned off *AUTOMATICALLY*!"
##
##
- id: Pantry Light AutoOff
  alias: "Pantry Light AutoOff"
  trigger:
  - platform: state
    entity_id: binary_sensor.pantry_door_sensor
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    entity_id: light.pantry
  - service: notify.slack_manorhaus
    data:
      message: "Pantry light turned off *AUTOMATICALLY*!"
##
##
- id: Upstairs Closet AutoOff
  alias: "Upstairs Closet AutoOff"
  trigger:
  - platform: state
    entity_id: light.upstairs_closet
    to: 'on'
    for:
      minutes: 10
  action:
  - service: light.turn_off
    entity_id: light.upstairs_closet
  - service: notify.slack_manorhaus
    data:
      message: "I turned off the upstairs closet light again. Sorry, ignore me. My whole thing is I just crave attention."
##
##
- id: Living Room Oil Burner AutoOff
  alias: "Living Room Oil Burner AutoOff"
  trigger:
  - platform: state
    entity_id: light.living_room__oil_burner_level
    to: 'on'
    for:
      minutes: 120
  action:
  - service: light.turn_off
    entity_id: light.living_room__oil_burner_level
  - service: notify.slack_manorhaus
    data:
      message: "@all turned off the dumb oil burner. Do you want to start a fire or something?!"
##
##
- id: Puppy Breakfast 
  alias: "Puppy Breakfast"
  trigger:
  - platform: time
    at: '08:00:00'
  action:
  - service: light.turn_on
    entity_id: light.pantry
  - service: notify.slack_manorhaus
    data:
      message: "It's Puppy Breakfast time!!"
##
##
- id: Doggo Dinnertime
  alias: "Doggo Dinnertime"
  trigger:
  - platform: time
    at: '20:00:00'
  action:
  - service: light.turn_on
    entity_id: light.pantry
  - service: notify.slack_manorhaus
    data:
      message: "It's Doggo Dinnertime!!"
##
##
- id: Upstairs Hallway AutoOff
  alias: "Upstairs Hallway AutoOff"
  trigger:
  - platform: state
    entity_id: binary_sensor.upstairs_occupancy
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    entity_id: light.upstairs_hallway
  - service: notify.slack_manorhaus
    data:
      message: "Upstairs Hallway Light turned off"
##
##
- id: Sunset
  alias: "Sunset"
  trigger:
  - platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
  - service: light.turn_on
    entity_id: group.living_room
  - service: notify.slack_manorhaus
    data:
      message: "Ugh. I activated the `Sunset` automation already! What else do you want me to do?"
##
##
- id: Upstairs Hallway AutoOn
  alias: "Upstairs Hallway AutoOn"
  trigger:
  - platform: state
    entity_id: binary_sensor.upstairs_occupancy
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.upstairs_hallway
  - service: notify.slack_manorhaus
    data:
      message: "Upstairs Hallway Light turned on"
##
##
- id: Living Room AutoOn
  alias: "Living Room AutoOn"
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_occupancy
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: group.living_room
  - service: notify.slack_manorhaus
    data:
      message: "There's people in the living room, so I turned on the lights.  UGH!"
##
##
- id: Living Room AutoOff
  alias: "Living Room AutoOff"
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_occupancy
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    entity_id: group.living_room
  - service: notify.slack_manorhaus
    data:
      message: "Since there's no one in the living room, I turned off the lights. UGH! UGH!"
##
##
#- id: Internet Speed Squaker Low
#  alias: "Internet Speed Squaker Low"
#  automation:
#  trigger: 
#    platform: template
#      - value_template: '{{ states.sensor.speedtest_download.state|float < 50}}'
#    action:                      
#      - service: notify.twitter_manorhaus
#      - data:
#        message: "What the hell? My download speed is '{{sensor.speedtest_download}}'Mb/sec? Someone needs to fix that... VERIZON."

##
##
