###
### Sensors!
###

#  Test our speed every 15 minutes
- platform: speedtest
  minute:
    - 0
    - 15
    - 30
    - 45
  monitored_conditions:
    - ping
    - download
    - upload
- platform: fastdotcom
  minute:
    - 0
    - 15
    - 30
    - 45
# Weather prediction
  - platform: yr

# Provides Date and Time
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_utc'

# Moon tracking
- platform: moon

# Are we getting mail today?
#- platform: usps

# - platform: lyft
  