###
### Sensors!
###

#  Test our speed every 15 minutes
- platform: speedtest
  minute:
    - 0
    - 15
    - 30
    - 45
  monitored_conditions:
    - ping
    - download
    - upload
- platform: fastdotcom
  minute:
    - 0
    - 15
    - 30
    - 45
# Weather prediction
- platform: yr

# Provides Date and Time
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_utc'

# Moon tracking
- platform: moon

# Package / Mail
- platform: ups
  username: !secret ups_username
  password: !secret ups_password

#- platform: usps

# - platform: lyft
  