###
### Sensors!
###

#  Test our speed every 15 minutes
- platform: speedtest
  minute:
    - 0
    - 15
    - 30
    - 45
  monitored_conditions:
    - ping
    - download
    - upload

- platform: fastdotcom
  minute:
    - 0
    - 15
    - 30
    - 45

- platform: google_wifi

- platform: template
  sensors:
    internet_state:
      entity_id: sensor.fastcom_download
      value_template: >-
        {% if states.sensor.fastcom_download.state|float > 0 %}
          online
        {% else %}
          offline
        {% endif %}

# Weather prediction
- platform: yr

# Provides Date and Time
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_utc'

# Moon tracking
- platform: moon

# Package / Mail
- platform: ups
  username: !secret ups_username
  password: !secret ups_password

- platform: fedex
  username: !secret fedex_username
  password: !secret fedex_password

- platform: ring
#- platform: usps

# - platform: lyft
