- alias: '[Switch] Office Xmas lights: on at sunset'
  initial_state: false
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.office_switch

- alias: '[Switch] Office Xmas lights: off at sunrise'
  initial_state: false
  hide_entity: true
  trigger:
    platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: switch.office_switch