- platform: template
  sensors:
    garage_left_color:
      entity_id: sensor.holiday_name
      value_template: >-
        {% if is_state("sensor.holiday_name", "new years") %}
          blue
        {% elif is_state("sensor.holiday_name", "mardi gras") %}
          purple
        {% elif is_state("sensor.holiday_name", "valentine's day") %}
          pink
        {% elif is_state("sensor.holiday_name", "lunar new year") %}
          red
        {% else %}
          white
        {% endif %}

- platform: template
  sensors:
    garage_right_color:
      value_template: >-
        {% if is_state("sensor.holiday_name", "new years") %}
          silver
        {% elif is_state("sensor.holiday_name", "mardi gras") %}
          purple
        {% elif is_state("sensor.holiday_name", "valentine's day") %}
          red
        {% elif is_state("sensor.holiday_name", "lunar new year") %}
          gold
        {% else %}
          white
        {% endif %}

- platform: template
  sensors:
    front_door_color:
      value_template: >-
        {% if is_state("sensor.holiday_name", "new years") %}
          gold
        {% elif is_state("sensor.holiday_name", "mardi gras") %}
          purple
        {% elif is_state("sensor.holiday_name", "valentine's day") %}
          pink
        {% elif is_state("sensor.holiday_name", "lunar new year") %}
          red
        {% else %}
          white
        {% endif %}
