- platform: template
  sensors:
    garage_left_holiday_color:
      entity_id: sensor.holiday_name
      value_template: >-
        {% if is_state("sensor.holiday_name", "new years") %}
          blue
        {% elif is_state("sensor.holiday_name", "mardi gras") %}
          purple
        {% elif is_state("sensor.holiday_name", "valentine's day") %}
          pink
        {% elif is_state("sensor.holiday_name", "lunar new year") %}
          red
        {% elif is_state("sensor.holiday_name", "st. patrick's day") %}
          green
        {% elif is_state("sensor.holiday_name", "memorial day") or is_state("sensor.holiday_name", "july 4th") %}
          red
        {% else %}
          white
        {% endif %}

- platform: template
  sensors:
    garage_right_holiday_color:
      value_template: >-
        {% if is_state("sensor.holiday_name", "new years") %}
          silver
        {% elif is_state("sensor.holiday_name", "mardi gras") %}
          gold
        {% elif is_state("sensor.holiday_name", "valentine's day") %}
          red
        {% elif is_state("sensor.holiday_name", "lunar new year") %}
          gold
        {% elif is_state("sensor.holiday_name", "st. patrick's day") %}
          green
        {% elif is_state("sensor.holiday_name", "memorial day") or is_state("sensor.holiday_name", "july 4th") %}
          white
        {% else %}
          white
        {% endif %}

- platform: template
  sensors:
    front_door_holiday_color:
      value_template: >-
        {% if is_state("sensor.holiday_name", "new years") %}
          gold
        {% elif is_state("sensor.holiday_name", "mardi gras") %}
          green
        {% elif is_state("sensor.holiday_name", "valentine's day") %}
          pink
        {% elif is_state("sensor.holiday_name", "lunar new year") %}
          red
        {% elif is_state("sensor.holiday_name", "st. patrick's day") %}
          green
        {% elif is_state("sensor.holiday_name", "memorial day") or is_state("sensor.holiday_name", "july 4th") %}
          blue
        {% else %}
          white
        {% endif %}
