- platform: template
  sensors:
    holiday_name:
      entity_id: sensor.date
      value_template: >-
        {% if is_state("sensor.simple_date_month", "12") and is_state("sensor.simple_date_day", "31") %}
          new years
        {% elif is_state("sensor.date", "2018-02-13") %}
          mardi gras
        {% elif is_state("sensor.date", "2018-02-09") %}
          TODAY!
        {% else %}
          nothing
        {% endif %}