- platform: template
  sensors:
    holiday_name:
      value_template: >-
        {% if is_state("sensor.simple_date_month", "12") and is_state("sensor.simple_date_day", "31") %}
          new years
        {% elif is_state("sensor.date", "2018-02-13") %}
          mardi gras
        {% elif is_state("sensor.simple_date_month", "2") and is_state("sensor.simple_date_day", "14") %}
          valentine's day
        {% elif is_state("sensor.date", "2018-02-16") %}
          lunar new year
        {% elif is_state("sensor.date", "2018-02-19") %}
          president's day
        {% elif is_state("sensor.simple_date_month", "3") and is_state("sensor.simple_date_day", "17") %}
          st. patrick's day
        {% elif is_state("sensor.date", "2018-05-26") or is_state("sensor.date", "2018-05-27") or  is_state("sensor.date", "2018-05-28") %}
          memorial day
        {% elif is_state("sensor.simple_date_month", "7") and is_state("sensor.simple_date_day", "4") %}
          july 4th
        {% elif is_state("sensor.simple_date_month", "10") %}
          halloween
        {% elif is_state("sensor.simple_date_month", "12") %}
          xmas
        {% elif is_state("sensor.date", "2018-11-06") %}
          voting day
        {% elif is_state("sensor.date", "2018-11-12") %}
          veteran's day
        {% else %}
          nothing
        {% endif %}
