- platform: template
  sensors:
    internet_state:
      value_template: >-
        {% if states.sensor.fastcom_download.state|float > 0 %}
          online
        {% else %}
          offline
        {% endif %}
