- platform: template
  sensors:
    simple_date_day:
      value_template: {{ strptime(states('sensor.date'), '%Y-%m-%d').day }}

- platform: template
  sensors:
    simple_date_month:
      value_template: {{ strptime(states('sensor.date'), '%Y-%m-%d').month }}

- platform: template
  sensors:
    simple_date_year:
      value_template: {{ strptime(states('sensor.date'), '%Y-%m-%d').year }}
