- alias: '[Switch] Guest Suite: toggle based on tempterature'
  trigger:
    platform: time
    minutes: '/10'
    seconds: 00
  action:
    - service: notify.coulter_slack
      data:
        message: >
          {% if states.sensor.guest_suite_temperature.state < states.sensor.home_temperature.state and states.climate.home.attributes.operation_mode == 'heat' %}
            Guest suite â˜ƒï¸ ( {{ states.sensor.guest_suite_temperature.state }} vs {{ states.sensor.home_temperature.state }} ) --> Heater on
          {% else %}
            Guest suite good --> Heater off
          {% endif %}
