- alias: '[Switch] Guest Suite: toggle based on tempterature'
  trigger:
    platform: time
    minutes: '/10'
    seconds: 00
  action:
    - service: notify.coulter_slack
      data:
        message: >
          {% if states.climate.home.attributes.operation_mode != 'heat' %}
            Not set to heat, ignoring.
          {% elif states('sensor.guest_suite_temperature')|float < states.climate.home.attributes.current_temperature %}
            Guest suite ☃️ (suite: {{ states.sensor.guest_suite_temperature.state }} vs target: {{ states.climate.home.attributes.current_temperature }}) --> Heater on
          {% else %}
            Guest suite good --> Heater off
          {% endif %}
