- alias: '[Lights] Front Lights: Dimmed christmas at sunset'
  initial_state: false
  trigger:
    platform: sun
    event: sunset
  action:
    - service: homeassistant.turn_on
      entity_id: script.front_lights_dimmed_christmas

- alias: '[Lights] Front Lights: Full christmas at sunset + 1hr'
  initial_state: false
  trigger:
    platform: sun
    event: sunset
    offset: '01:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: script.front_lights_christmas
