- alias: '[Lights] Front Lights: Sunset'
  trigger:
    platform: sun
    event: sunset
  action:
    - service: light.turn_on
      data:
        entity_id: light.front_door
        brightness_pct: 33
      data_template:
        color_name: "{{ states.sensor.front_door_holiday_color.state }}"
    - service: light.turn_on
      data:
        entity_id: light.garage_left
        brightness_pct: 33
      data_template:
        color_name: "{{ states.sensor.garage_left_holiday_color.state }}"
    - service: light.turn_on
      data:
        entity_id: light.garage_right
        brightness_pct: 33
      data_template:
        color_name: "{{ states.sensor.garage_right_holiday_color.state }}"

- alias: '[Lights] Front Lights: Sunset + 1hr'
  trigger:
    platform: sun
    event: sunset
    offset: '01:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.front_door
        brightness_pct: 100
      data_template:
        color_name: "{{ states.sensor.front_door_holiday_color.state }}"
    - service: light.turn_on
      data:
        entity_id: light.garage_left
        brightness_pct: 100
      data_template:
        color_name: "{{ states.sensor.garage_left_holiday_color.state }}"
    - service: light.turn_on
      data:
        entity_id: light.garage_right
        brightness_pct: 100
      data_template:
        color_name: "{{ states.sensor.garage_right_holiday_color.state }}"