- alias: '[Lights] Front Lights: Dimmed white at sunset'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:15:00'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Front door"
        scene_name: "Dimmed"
    - service: hue.hue_activate_scene
      data:
        group_name: "Garage"
        scene_name: "Dimmed"

- alias: '[Lights] Front Lights: Full white at sunset + 1hr'
  trigger:
    platform: sun
    event: sunset
    offset: '01:00:00'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Front door"
        scene_name: "Bright"
    - service: hue.hue_activate_scene
      data:
        group_name: "Garage"
        scene_name: "Bright"
