- alias: '[Lights] Front Lights: Dimmed color at sunset'
  trigger:
    platform: sun
    event: sunset
  action:
    - service: homeassistant.turn_on
      entity_id: script.front_lights_holiday_colors
    - service: light.turn_on
      data:
        entity_id:
          - light.front_door
          - light.garage_left
          - light.garage_right
        brightness_pct: 33

- alias: '[Lights] Front Lights: Full white at sunset + 1hr'
  trigger:
    platform: sun
    event: sunset
    offset: '01:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: script.front_lights_holiday_colors
    - service: light.turn_on
      data:
        entity_id:
          - light.front_door
          - light.garage_left
          - light.garage_right
        brightness_pct: 100