- alias: '[Lights] Front Lights: Half at midnight'
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.front_door
        brightness_pct: 50
    - service: light.turn_on
      data:
        entity_id: light.garage_left
        brightness_pct: 50
    - service: light.turn_on
      data:
        entity_id: light.garage_right
        brightness_pct: 50
