- alias: '[Lights] Front Lights: Dimmed new years at sunset'
  initial_state: false
  trigger:
    platform: sun
    event: sunset
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Front door"
        scene_name: "Dimmed New Years"
    - service: hue.hue_activate_scene
      data:
        group_name: "Garage"
        scene_name: "Dimmed New Years"

- alias: '[Lights] Front Lights: Full new years at sunset + 1hr'
  initial_state: false
  trigger:
    platform: sun
    event: sunset
    offset: '01:00:00'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Front door"
        scene_name: "New Years"
    - service: hue.hue_activate_scene
      data:
        group_name: "Garage"
        scene_name: "New Years"
